### ISSUE TITLE
do_one is named obtusely

### ISSUE THREAD

**Issue by EclectickMedia** [l4m3rx/python-ping#13]
# Obtuse naming and the issues it causes. 

Whether working with the software as a command line interface or via another software package, the naming scheme of `do_one` and `send_one_ping` cause a headache when trying to understand how to use the software.

This could be fixed easily if the private access functions (i.e `send_one_ping` and `receive_one_ping`) were refactored to include an underscore at the beginning of the name.

# Naming considerations. 

The names of `send_one_ping` and `recieve_one_ping` could likely be shortened to `_send` and `_recieve` respectively. The fact that more public access functions imply that  they are or could be used for more than one ping sequence allows them to be shortened to simply `ping`.

**Comment by l4m3rx** [comment]
Good point. 
https://github.com/l4m3rx/python-ping/commit/dc6177bc72fef4a3e2a7ee21c80d8b95cde68b2a
