### ISSUE TITLE
quiet_ping() loops

### ISSUE THREAD

**Issue by l4m3rx** [l4m3rx/python-ping#19]
quiet_ping() function cannot end.

Running 

> list(ping.quiet_ping('google.com', timeout=3000, count=3, numDataBytes=1300))

never exits.

**Comment by l4m3rx** [comment]
Due to the fact that quiet_ping() should run in background and we only care about the end result (and infinite quiet ping is not really something ppl will really need) maybe it will be better if we only keep verbose_ping() as generator and revert quiet_ping() to the old way....
@EclectickMedia  What do you think?

**Comment by l4m3rx** [comment]
I found the issue.
```
        if count is not None and i < count:
            i += 1
        elif count is not None:
            yield myStats.pktsSent
        elif count is not None and i >= count:
            break

```
Should be 
```

        if count is not None and i < count:
            i += 1
        elif count is not None and i >= count:
            break
        elif count is not None:
            yield myStats.pktsSent

```
Or it will never brake.

**Comment by EclectickMedia** [comment]
On the note of reverting `quiet_ping` to non-generator code,

I somewhat agree. I'm working with this repository in [my own code](www.github.com/eclectickmedia/pingstats) and have found `single_ping` more useful for extension anyways.

Im able to just create a generator that uses `single_ping` as many times as needed (in my case, generally infinitely as I am using the software to collect large datasets) via:
```python
import ping as pythonping  # I have another function named ping that is higher level than this
def generate_pings(address, **kwargs):
    i = 0
    while 1:
        yield pyping.single_ping('google.com', host_name, 3000, timeout, i, 64)
        i += 1
```
> I use this generator to generate my own statistics and visualize them via MatPlotLib *(unfortunately matplotlib doesnt like the frequency at which I can generate data.... `grumbles angrily`)*

**I was able to receive new data up to 70% more often than *Nix's implemented `ping` utility.**

As to your comment about no one needing to infinitely ping:

I need ping's to run for up to 6 months at a time to collect data and run analysis on the variance over time. I know several other IT pro's that maintain data about their response rate over time. This feature set is standard accross low level ping implementations across OS's. I think it is a feature worth implementing.

**Comment by l4m3rx** [comment]
How do you suggest we proceed ? 

I already did checkout ur project (PingStats) :+1:

**Comment by EclectickMedia** [comment]
I believe limiting features because you *think* the user won't need them sets you up for needing to add the feature later. 

May as well allow the user the option regardless of the number of people that use it.

**Comment by l4m3rx** [comment]
In this case I preffer going the KISS way.
quiet_ping() will be used mainly when ping.py is used as a lib... with that in mind, whoever is using it can just loop on single_ping() , so we're really saving him what... 2-3 lines of code...

**Comment by EclectickMedia** [comment]
Pretty much yeah. Thats fair.

**Comment by l4m3rx** [comment]
Closing this one for now.... we'll reopen it if needed.
