### ISSUE TITLE
We are dropping the TTL data during execution. 

### ISSUE THREAD

**Issue by EclectickMedia** [l4m3rx/python-ping#20]
Why aren't we collecting data about the TTL. 

Seems to me during `single_ping`'s runtime it would only take an extra line to calculate an average TTL. 

TTL's are useful to track to monitor packet forwarding in large networks.

**Comment by l4m3rx** [comment]
We're displaying the actual TTL data

# python ping.py 8.8.4.4

PYTHON PING 8.8.4.4 (8.8.4.4): 64 data bytes
64 bytes from 8.8.4.4: icmp_seq=0 **ttl=61** time=3.92 ms
64 bytes from 8.8.4.4: icmp_seq=1 **ttl=61** time=3.93 ms
64 bytes from 8.8.4.4: icmp_seq=2 **ttl=61** time=3.96 ms
^C
----8.8.4.4 PYTHON PING Statistics----
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip (ms)  min/avg/max = 3.9/3.9/4.0


(Terminated with signal 2)

# python ping.py 195.24.90.1      
PYTHON PING 195.24.90.1 (195.24.90.1): 64 data bytes
64 bytes from 195.24.90.1: icmp_seq=0 **ttl=64** time=0.19 ms
64 bytes from 195.24.90.1: icmp_seq=1 **ttl=64** time=0.26 ms
----195.24.90.1 PYTHON PING Statistics----
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip (ms)  min/avg/max = 0.2/0.2/0.3

**Comment by EclectickMedia** [comment]
We are displaying it, but we arent collecting the data into `MStats`.

TTL's can change over time.

**Comment by l4m3rx** [comment]
Can you show an example of what you have in mind?

**Comment by EclectickMedia** [comment]
For [my own software](https://github.com/EclectickMedia/PingStats), it would be nice to be able to retrieve, and log the TTL information.

The TTL information is retrieved from the call to `_recieve` as `iphTTL` here: (d735df8f6560df663bdb7e725a507084f4e0edae)
```
146                                                                                 
147     recvTime, dataSize, iphSrcIP, icmpSeqNumber, iphTTL \                       
148         = _receive(mySocket, my_ID, timeout, ipv6)                              
149
```

And is only used in a print statement here: (d735df8f6560df663bdb7e725a507084f4e0edae)
```
164                                                                                 
165             if verbose:                                                         
166                 print("%d bytes from %s: icmp_seq=%d ttl=%d time=%.2f ms" % (   
167                       dataSize, host_addr, icmpSeqNumber, iphTTL, delay)        
168                       )                                                         
169       
```
My proposed change would be to extend the return statement for `send_one` by returning the results of the request as a tuple after the delay value:
``` python
return delay, (recvTime, dataSize, host_addr, icmpSeqNumber, iphTTL)
```
Not only does this allow developers to access the TTL information, but it allows them to access the information about each request response as it is recieved. For example, right now my code needs to log a time as to when `single_ping` completes executing, but this information is already stored with `ping.single_ping.recvTime`, and I need access to the TTL information that is stored at `ping.single_ping.iphTTL`. 

This way, our code can be refactored to just use `single_ping()[0]` to access the delay value.

**Comment by l4m3rx** [comment]
Got for it  :+1:
