### ISSUE TITLE
Should we submit a pull to samuel/python-ping?

### ISSUE THREAD

**Issue by EclectickMedia** [l4m3rx/python-ping#21]
This repo's base is horribly out of date. 

This software seems to be the most recently, and heavily maintained branch of the software.

Is there any reason to not notify the base maintainer of new code? 

It would not only expand the current collaborators list, but it would allow this repository more hits via github's search.

**Comment by l4m3rx** [comment]
Sadly - dead repo.

**Comment by EclectickMedia** [comment]
Fair enough.
