### ISSUE TITLE
The current repository name breaks python import structures in python3 and above

### ISSUE THREAD

**Issue by EclectickMedia** [l4m3rx/python-ping#23]
The repositories use of a `-` in the name makes the user walk through additional actions to allow the repo to be imported. Forcing them to remove the `-` from the resulting folder of a `git clone`.

For example:
Performing `git clone https://github.com/l4m3rx/python-ping.git`, then running the following breaks the import structure.

```python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import python-ping
  File "<stdin>", line 1
    import python-ping
                 ^
SyntaxError: invalid syntax
```

Renaming the repo would fix this issue.

Even if we don't rename the repo, attention should be drawn to this flaw in the Readme.

**Comment by l4m3rx** [comment]
Any suggestions for a new name?

**Comment by EclectickMedia** [comment]
There are two simple names we could use:
1. `python_ping` *import accepts `_` as a valid character*
>Interpreter example
```
$ git clone https://github.com/l4m3rx/python-ping.git
Cloning into 'python-ping'...
remote: Counting objects: 398, done.
remote: Total 398 (delta 0), reused 0 (delta 0), pack-reused 398
Receiving objects: 100% (398/398), 113.05 KiB | 190.00 KiB/s, done.
Resolving deltas: 100% (227/227), done.
$ mv python-ping/ python_ping
$ python3
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import python_ping
```
2. `pythonping` *the simplest solution*
>Interpreter example
```
$ git clone https://github.com/l4m3rx/python-ping.git
...
$ mv python-ping/ pythonping/
$ python3
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pythonping
```

I am not sure what the easiest way to accomplish this would be via `GitHub`

**Comment by EclectickMedia** [comment]
We should be able to accomplish this change via the repository settings *(which I don't have access to)*.

**Comment by pepoluan** [comment]
For me, the easiest way is to notify potential users of this problem in the README, informing them that they should specify the dest dir name in `git clone`:

`git clone https://github.com/l4m3rx/python-ping.git python_ping`

with additional instruction to rename the dir if they had already cloned it without specifying the dest dir.

Renaming the repo will break many browser bookmarks, so I don't recommend doing that.

**Comment by EclectickMedia** [comment]
Fair point.

That may just be what we have to do.
