### ISSUE TITLE
Broadcast Pings do not appear to be working

### ISSUE THREAD

**Issue by bschollnick** [l4m3rx/python-ping#6]
I have not yet had a chance to test it on a different OS.  But under Mac OS X 10.10.4, with stock python Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin

I am unable to get broadcast pinging to acknowledge/display, the broadcasts from other systems.

For example, here is a standard broadcast ping:

nerv:~ Benjamin$ ping 192.168.1.255
PING 192.168.1.255 (192.168.1.255): 56 data bytes
64 bytes from 192.168.1.52: icmp_seq=0 ttl=64 time=0.077 ms
64 bytes from 192.168.1.38: icmp_seq=0 ttl=64 time=0.354 ms
64 bytes from 192.168.1.12: icmp_seq=0 ttl=64 time=0.520 ms
64 bytes from 192.168.1.1: icmp_seq=0 ttl=255 time=0.551 ms
64 bytes from 192.168.1.3: icmp_seq=0 ttl=255 time=0.555 ms
64 bytes from 192.168.1.2: icmp_seq=0 ttl=255 time=0.567 ms
64 bytes from 192.168.1.46: icmp_seq=0 ttl=64 time=1.976 ms
64 bytes from 192.168.1.25: icmp_seq=0 ttl=64 time=2.707 ms
64 bytes from 192.168.1.29: icmp_seq=0 ttl=64 time=206.287 ms
^C
--- 192.168.1.255 ping statistics ---
1 packets transmitted, 1 packets received, +8 duplicates, 0.0% packet loss
round-trip min/avg/max/stddev = 0.077/23.733/206.287/64.548 ms

Here is the results using python-ping:

nerv:python-ping-master Benjamin$ sudo python ping.py 192.168.1.255

PYTHON PING 192.168.1.255 (192.168.1.255): 64 data bytes
64 bytes from 192.168.1.52: icmp_seq=0 ttl=64 time=0 ms
64 bytes from 192.168.1.52: icmp_seq=1 ttl=64 time=0 ms
64 bytes from 192.168.1.52: icmp_seq=2 ttl=64 time=0 ms

----192.168.1.255 PYTHON PING Statistics----
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip (ms)  min/avg/max = 0/0.1/0

The only replies that are being returned, are from the host computer that is running the ping. 

I have glanced through the code, and don't see anything obvious...

**Comment by l4m3rx** [comment]
Sorry ....summer and all.... 
https://github.com/danharvey/pyping/commit/8d19ec1f57ac962a82f66cc323d50fc3c9684a09 Maybe this fixes the issue?

**Comment by l4m3rx** [comment]
opzy :)
Forgot to close it :D
