### ISSUE TITLE
How to hide 'Request timed out' message when calling quiet_ping() ?

### ISSUE THREAD

**Issue by insekt** [l4m3rx/python-ping#7]
quiet_ping() function is not really quite =) it prints 'Request timed out' message.
Is it possible to hide them when calling quiet_ping() but don't do it verbose_ping() ?

**Comment by insekt** [comment]
Proposed solution https://github.com/l4m3rx/python-ping/pull/8

**Comment by l4m3rx** [comment]
https://github.com/l4m3rx/python-ping/commit/6a73416e23f22c09497a4a8037ea305182e274f6
